{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    name: {{ .Values.namespace.name }}-label
  annotations:
    name: {{ .Values.namespace.name }}-annotation
{{- end -}}
