apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.deployment.labels.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deployment.labels.app }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
