namespace:
  name: demo-service

deployment:
  name: demo-service
  replicaCount: 1
  image:
    repository: "{{ .Values.image.repository }}"
    tag: "{{ .Values.image.tag }}"
    pullPolicy: IfNotPresent
  labels:
    app: demo-service

service:
  name: demo-service-svc
  type: LoadBalancer
  port: 8080
  targetPort: 808080

image:
  repository: "nginx"  # Default value, can be overridden by Helm --set or values file
  tag: "latest"        # Default value, can be overridden by Helm --set or values file
