# .github/workflows/deploy-helm.yml

name: Deploy Helm Chart to EKS (Using Access Keys)

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'
      - 'helm/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      TARGET_NAMESPACE: demo-service # Define namespace as variable

    steps:
      # Step 1: Check out code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4

      # Step 3: Update kubeconfig for EKS
      - name: Update kubeconfig for EKS
        run: |
          echo "Configuring kubectl for cluster: cc-eks"
          aws eks update-kubeconfig --name cc-eks --region $AWS_REGION

      # --- NEW STEP ---
      # Step 4: Ensure Namespace Exists using kubectl apply
      - name: Ensure Namespace Exists
        run: |
          echo "Ensuring namespace '${{ env.TARGET_NAMESPACE }}' exists..."
          # Use kubectl apply with a simple Namespace manifest via heredoc
          # Apply is idempotent and won't fail if the namespace already exists
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ${{ env.TARGET_NAMESPACE }}
          EOF
          echo "Namespace existence check complete."

# Step 5: Deploy Helm Chart
      - name: Deploy Helm Chart
        env:
          # Ensure this line correctly references your AWS Account ID secret
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY }}
          # TARGET_NAMESPACE: demo-service # If using env var for namespace
        run: |
          # Construct the full ECR image path using the AWS_ACCOUNT_ID variable
          FULL_ECR_IMAGE_PATH="${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPOSITORY_NAME}"

          echo "Deploying Helm chart 'demo-service' from './helm/demo-service'"
          echo "Target namespace: ${{ env.TARGET_NAMESPACE || 'demo-service' }}" # Use env var or default
          echo "Setting image repository to: ${FULL_ECR_IMAGE_PATH}" # Verify this uses the correct var
          echo "Setting image tag to: latest"

          helm upgrade --install demo-service helm/demo-service \
            --namespace ${{ env.TARGET_NAMESPACE || 'demo-service' }} \
            # Ensure this --set uses the variable containing the Account ID
            --set deployment.image.repository="${FULL_ECR_IMAGE_PATH}" \
            --set deployment.image.tag="latest"

          echo "Helm deployment command executed."