# .github/workflows/deploy-infra.yml

name: AWS Infrastructure Management (Using Access Keys)

on:
  push:
    branches:
      - master # Or your primary branch name (e.g., main)
    paths:
      - 'infra/**' # Trigger workflow only on changes within the infra directory
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (apply or destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

# Permissions: Only 'contents: read' is needed for checkout when using static keys
permissions:
  contents: read  # Required for actions/checkout

jobs:
  manage-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Set the working directory for ALL subsequent 'run' steps in this job.
        # Ensures terraform commands execute in ./infra
        working-directory: ./infra
    # Define AWS credentials and region as environment variables for the entire job
    # Terraform and AWS CLI will automatically pick these up.
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # Optional: Add if using temporary credentials
      AWS_REGION: us-east-1 # Set default region for AWS interactions

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the desired Terraform version
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.0.0' # Specify your required Terraform version

      # Step 3: REMOVED - Configure AWS credentials using OIDC is no longer needed

      # Step 4: Terraform Init (Runs in ./infra due to job defaults)
      # Initializes Terraform, downloads providers, and configures the S3 backend.
      # Uses AWS credentials defined in the job's 'env' block.
      - name: Terraform Init
        id: init
        run: terraform init -input=false -reconfigure -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="key=infra/terraform.tfstate" -backend-config="region=us-east-1"
        # No explicit env needed here, uses job env

      # Step 5: Terraform Plan (Runs in ./infra due to job defaults)
      # Creates an execution plan. Skips if the dispatched action is 'destroy'.
      - name: Terraform Plan
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action != 'destroy')
        run: terraform plan -out=tfplan -input=false
        env:
          # Pass non-credential variables needed by the Terraform configuration itself
          # TF_VAR_oidc_github_actions_role_arn: # REMOVED
          TF_VAR_admin_user_arns: ${{ secrets.ADMIN_USER_ARN }}       # Pass the SINGLE admin user ARN string
          TF_VAR_admin_k8s_username: ${{ secrets.ADMIN_K8S_USERNAME }}  # Pass the admin Kubernetes username string
          # TF_VAR_aws_region: us-east-1 # Not strictly needed if AWS_REGION is set globally

      # Step 6: Terraform Apply (Runs in ./infra due to job defaults)
      # Applies the changes defined in the plan. Skips if dispatched action is 'destroy'.
      - name: Terraform Apply
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action != 'destroy')
        run: terraform apply -auto-approve -input=false tfplan
        env:
          # Repeat non-credential TF_VARs needed during the apply phase
          TF_VAR_admin_user_arns: ${{ secrets.ADMIN_USER_ARN }}
          TF_VAR_admin_k8s_username: ${{ secrets.ADMIN_K8S_USERNAME }}
          # TF_VAR_aws_region: us-east-1

      # Step 7: Terraform Destroy (Runs in ./infra due to job defaults)
      # Destroys the managed infrastructure. Only runs if dispatched action is 'destroy'.
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
        env:
          # Repeat non-credential TF_VARs potentially needed during the destroy phase
          TF_VAR_admin_user_arns: ${{ secrets.ADMIN_USER_ARN }}
          TF_VAR_admin_k8s_username: ${{ secrets.ADMIN_K8S_USERNAME }}
          # TF_VAR_aws_region: us-east-1