name: Deploy Infrastructure to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:  # Allows manual triggering

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.0.0'

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.githubaws }}
          aws-region: us-east-1  # AWS region as specified

      - name: Terraform Init
        run: |
          cd infra
          terraform init

      - name: Terraform Plan
        run: |
          cd infra
          terraform plan -out=tfplan

      # - name: Terraform Apply
      #   run: |
      #     cd infra
      #     terraform apply -auto-approve tfplan